version: 0.2

phases:
  install:
    commands:
      - echo "Installing Node.js 18..."
      - curl -sL https://rpm.nodesource.com/setup_18.x | bash -
      - yum install -y nodejs
      - node -v
      - npm -v
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Building Vite project..."
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: dist
  discard-paths: yes
